project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - notebooks.qmd
    - assignments.qmd
    - assignment1.qmd
    - assignment2.qmd
    - assignment3.qmd
    - assignment4.qmd
   
    
website:
  title: ""
  search: false  
  

    
format: 
  html:
    theme: cosmo
    scss: styles.css
    



