project:
  type: website
  output-dir: docs
  render:
    - index.qmd
      
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 638
    file: index.qmd
    
format: 
  html:
    theme: cosmo
    scss: styles.css
    



